package kran_v2.classes;

import java.util.*;
import javax.annotation.Generated;

@Generated(value = { "de.iils.dc43.scriptrule.generator.JavaGenerator" }, date = "2014-11-24T15:37:12.278+0100")
@SuppressWarnings("all")
public interface Kran extends geometry.Component {
	
	public static final String MAST__PROP = "mast";
	public org.eclipse.uml2.uml.Property umlPropMast();
	public org.eclipse.uml2.uml.Slot umlSlotMast();
	public Mast getMast();
	public void setMast(Mast mast);
	public static final String UNTERBAU__PROP = "unterbau";
	public org.eclipse.uml2.uml.Property umlPropUnterbau();
	public org.eclipse.uml2.uml.Slot umlSlotUnterbau();
	public Unterbau getUnterbau();
	public void setUnterbau(Unterbau unterbau);
	public static final String HAUPTAUSLEGER__PROP = "hauptausleger";
	public org.eclipse.uml2.uml.Property umlPropHauptausleger();
	public org.eclipse.uml2.uml.Slot umlSlotHauptausleger();
	public Hauptausleger getHauptausleger();
	public void setHauptausleger(Hauptausleger hauptausleger);
	public static final String FAHRWERK__PROP = "fahrwerk";
	public org.eclipse.uml2.uml.Property umlPropFahrwerk();
	public org.eclipse.uml2.uml.Slot umlSlotFahrwerk();
	public raupe.classes.Fahrwerk getFahrwerk();
	public void setFahrwerk(raupe.classes.Fahrwerk fahrwerk);
	public static final String NEBENAUSLEGER__PROP = "nebenausleger";
	public org.eclipse.uml2.uml.Property umlPropNebenausleger();
	public org.eclipse.uml2.uml.Slot umlSlotNebenausleger();
	public Nebenausleger getNebenausleger();
	public void setNebenausleger(Nebenausleger nebenausleger);
	public static final String HATUNTERBAU__PROP = "hatunterbau";
	public org.eclipse.uml2.uml.Property umlPropHatunterbau();
	public org.eclipse.uml2.uml.Slot umlSlotHatunterbau();
	public Boolean isHatunterbau();
	public void setHatunterbau(Boolean hatunterbau);
	public static final String HATHAUPTAUSLEGER__PROP = "hathauptausleger";
	public org.eclipse.uml2.uml.Property umlPropHathauptausleger();
	public org.eclipse.uml2.uml.Slot umlSlotHathauptausleger();
	public Boolean isHathauptausleger();
	public void setHathauptausleger(Boolean hathauptausleger);
	public static final String SOLID__PROP = "solid";
	public org.eclipse.uml2.uml.Property umlPropSolid();
	public org.eclipse.uml2.uml.Slot umlSlotSolid();
	public Boolean isSolid();
	public void setSolid(Boolean solid);
	public static final String SCHWERPUNKTX__PROP = "schwerpunktx";
	public org.eclipse.uml2.uml.Property umlPropSchwerpunktx();
	public org.eclipse.uml2.uml.Slot umlSlotSchwerpunktx();
	public Double getSchwerpunktx();
	public void setSchwerpunktx(Double schwerpunktx);
	public static final String SCHWERPUNKTY__PROP = "schwerpunkty";
	public org.eclipse.uml2.uml.Property umlPropSchwerpunkty();
	public org.eclipse.uml2.uml.Slot umlSlotSchwerpunkty();
	public Double getSchwerpunkty();
	public void setSchwerpunkty(Double schwerpunkty);
	public static final String SCHWERPUNKTZ__PROP = "schwerpunktz";
	public org.eclipse.uml2.uml.Property umlPropSchwerpunktz();
	public org.eclipse.uml2.uml.Slot umlSlotSchwerpunktz();
	public Double getSchwerpunktz();
	public void setSchwerpunktz(Double schwerpunktz);
	public static final String MASTVOLUMEN__PROP = "mastvolumen";
	public org.eclipse.uml2.uml.Property umlPropMastvolumen();
	public org.eclipse.uml2.uml.Slot umlSlotMastvolumen();
	public Double getMastvolumen();
	public void setMastvolumen(Double mastvolumen);
	public static final String MASTDICHTE__PROP = "mastdichte";
	public org.eclipse.uml2.uml.Property umlPropMastdichte();
	public org.eclipse.uml2.uml.Slot umlSlotMastdichte();
	public Double getMastdichte();
	public void setMastdichte(Double mastdichte);
	public static final String MSCHWERPUNKTX__PROP = "mschwerpunktx";
	public org.eclipse.uml2.uml.Property umlPropMschwerpunktx();
	public org.eclipse.uml2.uml.Slot umlSlotMschwerpunktx();
	public Double getMschwerpunktx();
	public void setMschwerpunktx(Double mschwerpunktx);
	public static final String MSCHWERPUNKTY__PROP = "mschwerpunkty";
	public org.eclipse.uml2.uml.Property umlPropMschwerpunkty();
	public org.eclipse.uml2.uml.Slot umlSlotMschwerpunkty();
	public Double getMschwerpunkty();
	public void setMschwerpunkty(Double mschwerpunkty);
	public static final String MSCHWERPUNKTZ__PROP = "mschwerpunktz";
	public org.eclipse.uml2.uml.Property umlPropMschwerpunktz();
	public org.eclipse.uml2.uml.Slot umlSlotMschwerpunktz();
	public Double getMschwerpunktz();
	public void setMschwerpunktz(Double mschwerpunktz);
	public static final String MASTMASSE__PROP = "mastmasse";
	public org.eclipse.uml2.uml.Property umlPropMastmasse();
	public org.eclipse.uml2.uml.Slot umlSlotMastmasse();
	public Double getMastmasse();
	public void setMastmasse(Double mastmasse);
	public static final String MASSE__PROP = "masse";
	public org.eclipse.uml2.uml.Property umlPropMasse();
	public org.eclipse.uml2.uml.Slot umlSlotMasse();
	public Double getMasse();
	public void setMasse(Double masse);
	public static final String ARBEITSBEREICHX__PROP = "arbeitsbereichx";
	public org.eclipse.uml2.uml.Property umlPropArbeitsbereichx();
	public org.eclipse.uml2.uml.Slot umlSlotArbeitsbereichx();
	public Double getArbeitsbereichx();
	public void setArbeitsbereichx(Double arbeitsbereichx);
	public static final String MASTVORNE__PROP = "mastvorne";
	public org.eclipse.uml2.uml.Property umlPropMastvorne();
	public org.eclipse.uml2.uml.Slot umlSlotMastvorne();
	public Mast getMastvorne();
	public void setMastvorne(Mast mastvorne);
	public static final String LAST__PROP = "last";
	public org.eclipse.uml2.uml.Property umlPropLast();
	public org.eclipse.uml2.uml.Slot umlSlotLast();
	public Double getLast();
	public void setLast(Double last);
	public static final String INPUT__PROP = "input";
	public org.eclipse.uml2.uml.Property umlPropInput();
	public org.eclipse.uml2.uml.Slot umlSlotInput();
	public Input getInput();
	public void setInput(Input input);
	public static final String ABSPANNBOCK__PROP = "abspannbock";
	public org.eclipse.uml2.uml.Property umlPropAbspannbock();
	public org.eclipse.uml2.uml.Slot umlSlotAbspannbock();
	public Abspannbock getAbspannbock();
	public void setAbspannbock(Abspannbock abspannbock);
	public static final String VERBINDUNGSSEIL__PROP = "verbindungsseil";
	public org.eclipse.uml2.uml.Property umlPropVerbindungsseil();
	public org.eclipse.uml2.uml.Slot umlSlotVerbindungsseil();
	public Verbindungsseil getVerbindungsseil();
	public void setVerbindungsseil(Verbindungsseil verbindungsseil);
	public Kran mast_(Mast mast);
	public Kran unterbau_(Unterbau unterbau);
	public Kran hauptausleger_(Hauptausleger hauptausleger);
	public Kran fahrwerk_(raupe.classes.Fahrwerk fahrwerk);
	public Kran nebenausleger_(Nebenausleger nebenausleger);
	public Kran hatunterbau_(Boolean hatunterbau, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran hathauptausleger_(Boolean hathauptausleger, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran solid_(Boolean solid, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran schwerpunktx_(Double schwerpunktx, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran schwerpunkty_(Double schwerpunkty, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran schwerpunktz_(Double schwerpunktz, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mastvolumen_(Double mastvolumen, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mastdichte_(Double mastdichte, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mschwerpunktx_(Double mschwerpunktx, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mschwerpunkty_(Double mschwerpunkty, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mschwerpunktz_(Double mschwerpunktz, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mastmasse_(Double mastmasse, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran masse_(Double masse, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran arbeitsbereichx_(Double arbeitsbereichx, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran mastvorne_(Mast mastvorne);
	public Kran last_(Double last, org.eclipse.uml2.uml.Stereotype... slotStereos);
	public Kran input_(Input input);
	public Kran abspannbock_(Abspannbock abspannbock);
	public Kran verbindungsseil_(Verbindungsseil verbindungsseil);
	public Kran shape_(geometry.Shape shape);
	public Kran existingComponent_(geometry.ExistingComponent existingComponent);
	public Kran color_(geometry.Color color);
	public Kran primitiveShape_(geometry.Shape primitiveShape);
	public Kran userDefinedFeature_(geometry.UserDefinedFeature userDefinedFeature);
	public Kran sub_(geometry.TopologyElement... instancesToLink);
	public Kran sub_(List<geometry.TopologyElement> instancesToLink);
	public Kran sub_add_(geometry.TopologyElement instanceToLink);
}
